<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class Product extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules($check_id=null)
    {
        if ($check_id){
            return [
                'name'=>'required|max:20|min:2',
                'sn'=>[
                    'required',
                    'max:5',
                    'min:5',
                    Rule::unique('products')->ignore($check_id),
                ],
                'type'=>'required',
                'pro_price'=>'required|numeric',
                'sell_price'=>'required|numeric',
                'unit'=>'required|max:5',
                'inventory_alarm'=>'required|numeric'

            ];
        }else{
            return [
                'name'=>'required|max:20|min:2',
                'sn'=>'required|max:5|min:5|unique:products',
                'type'=>'required',
                'pro_price'=>'required|numeric',
                'sell_price'=>'required|numeric',
                'unit'=>'required|max:5',
                'inventory_alarm'=>'required|numeric'

            ];
        }
    }

    public function messages()
    {
       // return parent::messages(); // TODO: Change the autogenerated stub
    }
}
